<?php
/**
 * Implementation of hook_form_alter
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
    if($form_id=='comment_comment_form'){
        $form['actions']['submit']['#value']=t('comment');
        }
}
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function mymodule_help($path, $arg) {
    switch ($path) {
      case "help.page.mymodule":
        return '' . t("Hello, This is my Second custom hook") . '';
        break;
    }
  }
  /**
   * @file
 * Implementation of hook_cron
 */
  function mymodule_cron() {
    $slogan = \Drupal::service('config.factory')->getEditable('system.site')->get('slogan');
    // if(is_numeric($slogan)){
    //     $slogan=$slogan+1;
    //     \Drupal::service('config.factory')->getEditable('system.site')->set('slogan', $slogan)->save();
    // }
    // else{
    //     \Drupal::service('config.factory')->getEditable('system.site')->set('slogan', 0)->save();
    //     }
    $slogan="Hello How Are You !!";
    \Drupal::service('config.factory')->getEditable('system.site')->set('slogan', $slogan)->save();
    }